stages:
- name: Docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sa-logic:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
- name: LoadBalancer
  steps:
  - applyYamlConfig:
      path: ./deployment-lb.yaml
- name: Autoscale
  steps:
  - applyYamlConfig:
      path: ./deployment-sc.yaml
timeout: 60
notification: {}
