apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/ingressState: '{"bG9naWMvc2EveGlwLmlvLy81MDUw":"deployment:sa:sentiment-analysis-logic"}'
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.103"],"port":80,"protocol":"HTTP","serviceName":"sa:ingress-9023f0d5ff84524e696f2a4418f7418b","ingressName":"sa:logic","hostname":"logic.sa.192.168.1.103.xip.io","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"labels":{"cattle.io/creator":"norman"},"name":"logic","namespace":"sa"},"spec":{"rules":[{"host":"xip.io","http":{"paths":[{"backend":{"serviceName":"ingress-77d29b22a5f6c67c093aa5707e6ed62d","servicePort":5050},"path":"/"}]}}]},"status":{"loadBalancer":{}}}'
  labels:
    cattle.io/creator: norman
  name: logic
  namespace: sa
spec:
  rules:
  - host: logic.sa.192.168.1.103.xip.io
    http:
      paths:
      - backend:
          serviceName: ingress-9023f0d5ff84524e696f2a4418f7418b
          servicePort: 5050
status:
  loadBalancer: {}