apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-js2ch
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.84"],"port":30100,"protocol":"TCP","serviceName":"sa:sentiment-analysis-logic-nodeport","allNodes":true}]'
  creationTimestamp: "2019-05-23T10:37:25Z"
  generation: 2
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-sa-sentiment-analysis-logic
  name: sentiment-analysis-logic
  namespace: sa
  resourceVersion: "41005"
  selfLink: /apis/apps/v1beta2/namespaces/sa/deployments/sentiment-analysis-logic
  uid: c16e62c9-7d46-11e9-963c-080027b2e727
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-sa-sentiment-analysis-logic
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-05-23T10:37:25Z"
        field.cattle.io/ports: '[[{"containerPort":5050,"dnsName":"sentiment-analysis-logic-nodeport","kind":"NodePort","name":"5050tcp301001","protocol":"TCP","sourcePort":30100}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-sa-sentiment-analysis-logic
    spec:
      containers:
      - image: serg470/sentiment-analysis-logic:kuber
        imagePullPolicy: Always
        name: sentiment-analysis-logic
        ports:
        - containerPort: 5050
          name: 5050tcp301001
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2019-05-23T10:37:26Z"
    lastUpdateTime: "2019-05-23T10:37:26Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2019-05-23T10:37:25Z"
    lastUpdateTime: "2019-05-23T10:37:26Z"
    message: ReplicaSet "sentiment-analysis-logic-668c5c96df" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
